name: Yarn Test
on:
  push:
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: "bun install"
        run: |
          curl -fsSL https://bun.sh/install | bash
      - name: Install dependencies
        run: bun install
      - name: Run tests
        run: |
          cd  packages/canvas-engine
          bun test